apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: server-demo-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: khoanlm2.demo
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: server-demo
            port:
              number: 80