apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: server-demo-ingress
  namespace: ingress-controller
spec:
  rules:
  - host: khoanlm2.local
    http: 
      paths:
      - path: /
        backend:
          serviceName: server-demo
          servicePort: 80