apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: server-demo-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/affinity-mode: persistent
spec:
  rules:
  - host: khoanlm2.demo
    http:
      paths:
      - path: /
        backend:
          serviceName: server-demo
          servicePort: 80