apiVersion: apps/v1alpha1
kind: Rollout
metadata:
  name: app-rollout
spec:
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: { duration: 30s } 
      - pause: { duration: 30s } 
      - pause: { duration: 30s }