apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: ingress-app
spec:
  replicas: 4
  selector: 
    matchLabels:
      name: ingress
  template:
    metadata:
      labels:
        name: ingress
    spec:
      containers:
      - name: ingress-red
        image: red/server:1.0
  strategy:
    canary:
      stableService: ingress-app-stable
      canaryService: ingress-app-canary
      steps:
      - setWeight: 10
      - pause: { duration: 60}
      - setWeight: 10
      - pause: { duration: 30}
