apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: server-demo
spec:
  selector:
    matchLabels:
      app: server-demo
  replicas: 5
  template:
    metadata:
      labels:
        app: server-demo
    spec:
      containers:
      - name: realtimeapp
        image: server:blue
        ports:
        - containerPort: 8080
  strategy:
    canary:
      canaryService: server-demo-canary
      #trafficRouting:
        #nginx:
          #stableIngress: realtimeapp-ingress
      steps:
      - setWeight: 50
      - pause: {}