apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: ingress-rollout
spec:
  replicas: 5
  revisionHistoryLimit: 1
  selector: 
    matchLabels:
      app: ingress-rollout
  template:
    metadata:
      labels:
        app: ingress-rollout
    spec:
      containers:
      - name: ingress-rollout
        image: red/server:1.0
  strategy:
    canary:
      stableService: ingress-stable
      canaryService: ingress-canary
      steps:
      - setWeight: 20
      - pause: { duration: 30}
      - setWeight: 50
      - pause: { duration: 30}
