apiVersion: v1
kind: Service
metadata:
  name: ingress
  labels:
    name: ingress
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    name: ingress
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-canary
  labels:
    name: ingress
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    name: ingress
  type: NodePort