apiVersion: v1
kind: Service
metadata:
  name: ingress-app-stable
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    name: ingress
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-app-canary
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    name: ingress